# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: md5
        # FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                default_target_path: /user/in
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        #这里加不需要登录就能访问的路由
        - { path: ^/控制器的名称/(同步通知路由|异步通知路由)$, roles: IS_AUTHENTICATED_ANONYMOUSLY } 
       

       #- { path: ^/home, roles: ROLE_USER } # role是用户需要具备的角色，登录成功默认会有ROLE_USER
       # - { path: ^/account/pictures/index, roles: ROLE_SUPER_ADMIN }
       # - { path: ^/account/course, roles: ROLE_SUPER_ADMIN }
       # - { path: ^/account/course/new, roles: ROLE_SUPER_ADMIN }