n acme_web_ui_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeWebUIBundle:Default:index }

#video部分    

video_index_path:
  path: '/video/index/{id}'
  defaults: { _controller: AcmeWebUIBundle:Video:index } 

#record部分

record_index_path:
  path: '/record/index'
  defaults: { _controller: AcmeWebUIBundle:Record:index }  

#reserve部分

reserve_index_path:
  path: '/reserve/index'
  defaults: { _controller: AcmeWebUIBundle:Reserve:index }  

#role部分  

role_index_path:
  path: '/role/index'
  defaults: { _controller: AcmeWebUIBundle:Role:index }

role_edit_path:
  path: '/role/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Role:edit } 

role_create_path:
  path: '/role/create'
  defaults: { _controller: AcmeWebUIBundle:Role:create } 

role_delete_path:
  path: '/role/{id}'
  defaults: { _controller: AcmeWebUIBundle:Role:delete }
  requirements:
      _method:  DELETE   

#group部分

group_index_path:
    path: '/group/index'
    defaults: { _controller: AcmeWebUIBundle:Group:index} 

group_edit_path:
  path: '/group/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Group:edit } 

group_create_path:
  path: '/group/create'
  defaults: { _controller: AcmeWebUIBundle:Group:create } 

group_delete_path:
  path: '/group/{id}'
  defaults: { _controller: AcmeWebUIBundle:Group:delete }
  requirements:
      _method:  DELETE   

#account部分

account_index_path:
  path: '/account/index'
  defaults: { _controller: AcmeWebUIBundle:Account:index }

#course_item部分

item_index_path:
  path: '/item/index'
  defaults: { _controller: AcmeWebUIBundle:Item:index }

item_edit_path:
  path: '/item/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Item:edit } 

item_create_path:
  path: '/item/create'
  defaults: { _controller: AcmeWebUIBundle:Item:create } 

item_delete_path:
  path: '/item/{id}'
  defaults: { _controller: AcmeWebUIBundle:Item:delete }
  requirements:
      _method:  DELETE 

#course 部分

course_index_path:
  path: '/course/index'
  defaults: { _controller: AcmeWebUIBundle:Course:index }

course_edit_path:
  path: '/course/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Course:edit } 

course_create_path:
  path: '/course/create'
  defaults: { _controller: AcmeWebUIBundle:Course:create }  

course_delete_path:
  path: '/course/{id}'
  defaults: { _controller: AcmeWebUIBundle:Course:delete }
  requirements:
      _method:  DELETE

#teacher 部分

teacher_index_path:
  path: '/teacher/index'
  defaults: { _controller: AcmeWebUIBundle:Teacher:index } 

teacher_edit_path:
  path: '/teacher/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Teacher:edit } 

teacher_create_path:
  path: '/teacher/create'
  defaults: { _controller: AcmeWebUIBundle:Teacher:create }  

teacher_delete_path:
  path: '/teacher/{id}'
  defaults: { _controller: AcmeWebUIBundle:Teacher:delete }
  requirements:
      _method:  DELETE

#category_item部分

subcategory_index_path:
  path: '/subcategory/index'
  defaults: { _controller: AcmeWebUIBundle:Subcategory:index } 

subcategory_edit_path:
  path: '/subcategory/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Subcategory:edit }   

subcategory_create_path:
  path: '/subcategory/create'
  defaults: { _controller: AcmeWebUIBundle:Subcategory:create }

subcategory_delete_path:
  path: '/subcategory/{id}'
  defaults: { _controller: AcmeWebUIBundle:Subcategory:delete }
  requirements:
      _method:  DELETE

#category部分

category_index_path:
  path: '/category/index'
  defaults: { _controller: AcmeWebUIBundle:Category:index }

category_create_path:
  path: '/category/create'
  defaults: { _controller: AcmeWebUIBundle:Category:create }

category_edit_path:
  path: '/category/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Category:edit }

category_delete_path:
  path: '/category/{id}'
  defaults: { _controller: AcmeWebUIBundle:Category:delete }
  requirements:
      _method:  DELETE

#进入后台

user_in_path:
  path: '/user/in'
  defaults: { _controller: AcmeWebUIBundle:User:in }

user_text_path:
  path: '/user/text'
  defaults: { _controller: AcmeWebUIBundle:User:text }

user_auth_path:
  path: '/user/{id}/auth'
  defaults: { _controller: AcmeWebUIBundle:User:auth }

user_path:
  path: '/admin'
  defaults: { _controller: AcmeWebUIBundle:User:admin }

user_index_path:
  path: '/user/index'
  defaults: { _controller: AcmeWebUIBundle:User:index }

user_edit_path:
  path: '/user/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:User:edit }

user_create_path:
  path: '/user/create'
  defaults: { _controller: AcmeWebUIBundle:User:create }

user_reset_path:
  path: '/user/{id}/reset'
  defaults: { _controller: AcmeWebUIBundle:User:reset }

user_delete_path:
  path: '/user/{id}'
  defaults: { _controller: AcmeWebUIBundle:User:delete }
  requirements:
      _method:  DELETE

#前台页面

front_path:
  path: '/'
  defaults: { _controller: AcmeWebUIBundle:Front:index }

front_course_path:
  path: '/courses'
  defaults: { _controller: AcmeWebUIBundle:Front:course }

front_teacher_path:
  path: '/teachers'
  defaults: { _controller: AcmeWebUIBundle:Front:teacher }

front_about_path:
  path: '/about'
  defaults: { _controller: AcmeWebUIBundle:Front:about }

front_info_path:
  path: '/info'
  defaults: { _controller: AcmeWebUIBundle:Front:info }

front_mobile_path:
  path: '/mobile'
  defaults: { _controller: AcmeWebUIBundle:Mobile:index }

front_mobile_category_path:
  path: '/mobile/category'
  defaults: { _controller: AcmeWebUIBundle:Mobile:category }

front_mobile_teacher_path:
  path: '/mobile/teacher/'
  defaults: { _controller: AcmeWebUIBundle:Mobile:teacher }

front_mobile_teacher_info_path:
  path: '/mobile/teacher/{id}'
  defaults: { _controller: AcmeWebUIBundle:Mobile:teacherinfo }

front_mobile_course_path:
  path: '/mobile/course/{id}'
  defaults: { _controller: AcmeWebUIBundle:Mobile:course }

front_mobile_about_path:
  path: '/mobile/aboutus'
  defaults: { _controller: AcmeWebUIBundle:Mobile:about }